### ISSUE TITLE
error running `npm run dev:hapi`

### ISSUE THREAD

**Issue by bkinsey808** [nnance/express-hapi-graphql#1]
Same error happens when running `npm run dev:express`

```
bkinsey@kinsey-Inspiron-3551:~/opt/nnance/express-hapi-graphql$ npm run dev:hapi
> graphql-express-hapi@0.0.1 dev:hapi /home/bkinsey/opt/nnance/express-hapi-graphql
> nodemon ./dist/hapi.js

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./dist/hapi.js`
module.js:440
    throw err;
    ^

Error: Cannot find module 'graphql'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bkinsey/opt/nnance/express-hapi-graphql/dist/core/graphqlServer.js:2:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nnance** [comment]
@bkinsey808 just pushed a fix to include the module in package.json.  Give it a try now

**Comment by bkinsey808** [comment]
Works, thanks.
